### ISSUE TITLE
Reinforcement Learning still suffer from Errno 104 reset by peers

### ISSUE THREAD

**Issue by hantao-zhou** [haosulab/ManiSkill#176] opened 2023-12-08 16:37 UTC
The rl tutorial both in python and colab notebooks suffer from this error

**Comment by StoneT2000** [comment] 2023-12-08 21:51
can you share the full error log? this error is usually raised by stable baselines if i remember correctly, and it happens if the subprocess (running a parallel env) reaches an error

**Comment by StoneT2000** [comment] 2023-12-08 22:38
I just tried running https://colab.research.google.com/github/haosulab/ManiSkill2/blob/main/examples/tutorials/2_reinforcement_learning.ipynb (this is the one you tested with correct?) and am not able to reproduce the error. Trained a policy and it was successful

**Comment by StoneT2000** [comment] 2024-01-21 02:03
Closing the issue for now

**Closed as completed by StoneT2000** 2024-01-21 02:03 UTC
Labels: bug
